#!/usr/bin/env php
<?php

use PNixx\Daemon\Cli;

// Find and initialize Composer
$files = array(
	__DIR__ . '/../../vendor/autoload.php',
	__DIR__ . '/../../../autoload.php',
	__DIR__ . '/../../../../autoload.php',
	__DIR__ . '/../vendor/autoload.php',
);

foreach( $files as $file ) {
	if( file_exists($file) ) {
		require_once $file;
		break;
	}
}

if (!class_exists('Composer\Autoload\ClassLoader', false)) {
	die(
		'You need to set up the project dependencies using the following commands:' . PHP_EOL .
		'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
		'php composer.phar install' . PHP_EOL
	);
}

//Server class
class Server extends PNixx\Daemon\Daemon {

	public function run() {
		while( !$this->stop ) {
			//working process
		}
	}

	protected function onShutdown() {

	}
}
//--->

$cli = new Cli;
if( $cli->arguments->get('help') ) {
	$cli->usage();
} else {
	$server = new Server($cli);
	$server->run();
}